backend:
  name: turbo-github
  turbo_site_id: dcb06326-3e52-4098-8d82-3121bc69ed86
  branch: main

media_folder: "uploads"
public_folder: "/goodluck-research/uploads"

collections:
  - name: "articles"
    label: "文章"
    folder: "content/articles"
    create: true
    slug: "{{slug}}"

    fields:
      - label: "標題"
        name: "title"
        widget: "string"

      - label: "發布日期"
        name: "date"
        widget: "datetime"

      - label: "發布區域"
        name: "category"
        widget: "select"
        options:
          - label: "📖 占卜桌上的故事"
            value: "story"

          - label: "🟠 好運琥珀"
            value: "amber"

          - label: "🎪 好運生活日"
            value: "life-day"

      - label: "文章內容"
        name: "body"
        widget: "richtext"
        editor_components:
          - "code-block"
          - "resizable-image"
